cas.authn.jdbc.query[0].driver-class=com.mysql.cj.jdbc.Driver
cas.authn.jdbc.query[0].url=jdbc:mysql://mysql.staff-center-test.svc.cluster.local:3306/staff_center_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
cas.authn.jdbc.query[0].user=staff_center
cas.authn.jdbc.query[0].password=
cas.authn.jdbc.query[0].sql=select staff_code as username, null as user_pwd, * from staff_bind_we_chat where we_chat_user_id=?
cas.authn.jdbc.query[0].field-password=user_pwd

wecom.binding.url=https://your-wechat-binding-url